=begin
#Braze

#Track users, send messages, export data, and more

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

module BrazeClient
  VERSION = '0.1.1'
end
