=begin
#Braze

#Track users, send messages, export data, and more

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Braze::RestApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RestApi' do
  before do
    # run before each test
    @api_instance = Braze::RestApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RestApi' do
    it 'should create an instance of RestApi' do
      expect(@api_instance).to be_instance_of(Braze::RestApi)
    end
  end

  # unit tests for users_track
  # Record custom events, purchases, and update user profile attributes
  # @param users_track_request 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'users_track test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
