=begin
#Braze

#Track users, send messages, export data, and more

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Braze::Identifier
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Braze::Identifier do
  describe '.openapi_one_of' do
    it 'lists the items referenced in the oneOf array' do
      expect(described_class.openapi_one_of).to_not be_empty
    end
  end

  describe '.build' do
    it 'returns the correct model' do
    end
  end
end
