=begin
#Braze

#Track users, send messages, export data, and more

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Braze::IdentifierOneOf2
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Braze::IdentifierOneOf2 do
  let(:instance) { Braze::IdentifierOneOf2.new }

  describe 'test an instance of IdentifierOneOf2' do
    it 'should create an instance of IdentifierOneOf2' do
      expect(instance).to be_instance_of(Braze::IdentifierOneOf2)
    end
  end
  describe 'test attribute "braze_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
