=begin
#Braze

#Track users, send messages, export data, and more

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BrazeClient::UsersExternalIdsRemoveResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BrazeClient::UsersExternalIdsRemoveResponse do
  let(:instance) { BrazeClient::UsersExternalIdsRemoveResponse.new }

  describe 'test an instance of UsersExternalIdsRemoveResponse' do
    it 'should create an instance of UsersExternalIdsRemoveResponse' do
      expect(instance).to be_instance_of(BrazeClient::UsersExternalIdsRemoveResponse)
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "removal_errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "removed_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
