=begin
#Braze

#Track users, send messages, export data, and more

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BrazeClient::UsersExternalIdsRenameResponseExternalIds
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BrazeClient::UsersExternalIdsRenameResponseExternalIds do
  let(:instance) { BrazeClient::UsersExternalIdsRenameResponseExternalIds.new }

  describe 'test an instance of UsersExternalIdsRenameResponseExternalIds' do
    it 'should create an instance of UsersExternalIdsRenameResponseExternalIds' do
      expect(instance).to be_instance_of(BrazeClient::UsersExternalIdsRenameResponseExternalIds)
    end
  end
  describe 'test attribute "current_external_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "new_external_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
