=begin
#Braze

#Track users, send messages, export data, and more

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

# Common files
require 'braze_api_client/api_client'
require 'braze_api_client/api_error'
require 'braze_api_client/version'
require 'braze_api_client/configuration'

# Models
require 'braze_api_client/models/attributes'
require 'braze_api_client/models/attributes_array'
require 'braze_api_client/models/attributes_current_location'
require 'braze_api_client/models/attributes_facebook'
require 'braze_api_client/models/attributes_push_tokens'
require 'braze_api_client/models/attributes_twitter'
require 'braze_api_client/models/event'
require 'braze_api_client/models/events_array'
require 'braze_api_client/models/general_error'
require 'braze_api_client/models/identifier'
require 'braze_api_client/models/identifier_one_of'
require 'braze_api_client/models/identifier_one_of1'
require 'braze_api_client/models/identifier_one_of2'
require 'braze_api_client/models/inline_response200'
require 'braze_api_client/models/users_track_request'

# APIs
require 'braze_api_client/api/rest_api'

module Braze
  class << self
    # Customize default settings for the SDK using block.
    #   Braze.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
